-- Daily Fortunes Q1 2025 - January
-- Total Records: 372 (12 zodiac signs × 31 days)
-- Generated with unique daily variations, Korean holidays, and historical figure metaphors

-- Table structure (for reference)
/*
CREATE TABLE daily_fortunes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    zodiac_id INT NOT NULL,
    zodiac_name VARCHAR(20) NOT NULL,
    overall_fortune TEXT NOT NULL,
    love_fortune TEXT NOT NULL,
    money_fortune TEXT NOT NULL,
    work_fortune TEXT NOT NULL,
    health_fortune TEXT NOT NULL,
    love_score INT NOT NULL CHECK (love_score BETWEEN 60 AND 95),
    money_score INT NOT NULL CHECK (money_score BETWEEN 60 AND 95),
    work_score INT NOT NULL CHECK (work_score BETWEEN 60 AND 95),
    health_score INT NOT NULL CHECK (health_score BETWEEN 60 AND 95),
    lucky_color VARCHAR(20) NOT NULL,
    lucky_number INT NOT NULL CHECK (lucky_number BETWEEN 1 AND 99),
    lucky_time VARCHAR(20) NOT NULL,
    daily_advice TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
*/

-- January 1, 2025 - New Year's Day (Wednesday)
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-01-01', 1, 'Aries', 'The new year ignites your pioneering spirit like a great military strategist planning their next campaign. Fresh beginnings await those who dare to charge forward with unwavering determination.', 'A passionate encounter may spark unexpected romance, channeling the bold energy of history''s greatest lovers.', 'New financial opportunities emerge through courageous investments and calculated risks.', 'Leadership roles beckon as your innovative ideas gain recognition from colleagues and superiors.', 'High energy levels fuel your ambitious resolutions, but remember to pace yourself for the marathon ahead.', 88, 82, 90, 85, 'Crimson Red', 21, '6:30 AM', 'Channel your inner warrior today - bold actions taken now set the tone for the entire year.'),

('2025-01-01', 2, 'Taurus', 'Like a master craftsman beginning a new masterpiece, you approach this year with steady hands and artistic vision. Patience and persistence will be your greatest allies.', 'Stable relationships deepen through consistent affection and practical gestures of care.', 'Solid financial foundations strengthen through conservative but wise investment choices.', 'Your methodical approach to projects earns respect and delivers reliable results.', 'Focus on building sustainable health habits rather than dramatic changes.', 75, 88, 82, 80, 'Forest Green', 14, '10:15 AM', 'Build your dreams one steady step at a time - consistency outshines flash today.'),

('2025-01-01', 3, 'Gemini', 'Your quick wit sparkles like a brilliant orator captivating audiences with clever wordplay. Communication channels open wide, connecting you to new networks and opportunities.', 'Intellectual chemistry ignites romance through engaging conversations and shared interests.', 'Multiple income streams create financial diversity and security through varied ventures.', 'Your adaptability and networking skills open doors to collaborative projects.', 'Mental stimulation energizes you more than physical exercise today.', 85, 78, 87, 77, 'Electric Blue', 33, '2:20 PM', 'Let your curiosity lead the way - the most interesting discoveries come from unexpected questions.'),

('2025-01-01', 4, 'Cancer', 'Like a nurturing sovereign protecting their realm, you create emotional security for yourself and loved ones. Your intuitive wisdom guides important family decisions.', 'Deep emotional connections flourish through genuine vulnerability and caring gestures.', 'Real estate and home-based investments show promising potential for growth.', 'Your empathetic leadership style builds strong team loyalty and cooperation.', 'Emotional wellness takes priority - honor your feelings and seek supportive environments.', 80, 83, 79, 88, 'Pearl White', 7, '9:45 PM', 'Trust your intuition today - your emotional compass points toward true north.'),

('2025-01-01', 5, 'Leo', 'Your regal presence commands attention like a beloved entertainer taking center stage. Confidence radiates from within, inspiring others to follow your lead.', 'Dramatic romantic gestures create memorable moments that strengthen passionate bonds.', 'Creative endeavors and entertainment investments yield unexpected returns.', 'Your charismatic presentation skills win over important clients and stakeholders.', 'Vitality runs high, but avoid overexertion in pursuit of perfection.', 92, 80, 85, 83, 'Royal Gold', 19, '12:00 PM', 'Shine your light boldly today - the world needs your unique brand of inspiration.'),

('2025-01-01', 6, 'Virgo', 'Like a dedicated humanitarian organizing relief efforts, your attention to detail serves a greater purpose. Methodical planning transforms lofty goals into achievable steps.', 'Practical acts of service deepen romantic connections more than grand gestures.', 'Careful budgeting and systematic savings create a strong foundation for future growth.', 'Your analytical skills identify inefficiencies that others overlook, earning professional recognition.', 'Establishing healthy routines now prevents issues later in the year.', 74, 87, 91, 86, 'Navy Blue', 6, '7:30 AM', 'Perfect your craft through patient practice - excellence emerges from countless small improvements.'),

('2025-01-01', 7, 'Libra', 'Your diplomatic grace resembles a peace-making visionary bringing harmony to discord. Beauty and balance guide your decisions toward elegant solutions.', 'Relationships benefit from fair compromise and mutual respect for different perspectives.', 'Partnership investments and shared financial goals create mutual prosperity.', 'Your ability to see all sides of issues makes you invaluable in conflict resolution.', 'Seek balance between activity and rest to maintain optimal energy levels.', 86, 81, 84, 82, 'Rose Pink', 22, '4:15 PM', 'Find the middle path today - harmony emerges when opposing forces find their balance.'),

('2025-01-01', 8, 'Scorpio', 'Intense transformation energy flows through you like a revolutionary artist reinventing their medium. Hidden truths surface, revealing paths to profound change.', 'Deep psychological connections transcend superficial attractions, creating soul-level bonds.', 'Investigative research uncovers hidden investment opportunities with substantial potential.', 'Your penetrating insights expose underlying problems, leading to comprehensive solutions.', 'Emotional healing work accelerates physical recovery and overall vitality.', 89, 85, 88, 84, 'Deep Purple', 8, '11:30 PM', 'Embrace transformation today - what dies in you makes room for something more powerful to be born.'),

('2025-01-01', 9, 'Sagittarius', 'Your adventurous spirit soars like an explorer discovering new continents of possibility. Philosophical insights expand your worldview and inspire bold ventures.', 'Cultural differences become bridges to romance rather than barriers to connection.', 'International investments and educational pursuits promise long-term financial rewards.', 'Your visionary ideas inspire teams to achieve beyond their perceived limitations.', 'Physical adventure and outdoor activities energize both body and spirit.', 87, 79, 86, 89, 'Turquoise', 29, '6:00 AM', 'Aim for distant horizons today - your arrow flies furthest when released with complete faith.'),

('2025-01-01', 10, 'Capricorn', 'Steadfast determination propels you toward success like a civil rights leader pursuing justice through persistent action. Your reputation builds through consistent excellence.', 'Mature relationships deepen through shared goals and mutual respect for ambitions.', 'Long-term investment strategies and retirement planning show excellent prospects.', 'Your disciplined approach to projects earns recognition from industry leaders.', 'Structure and routine optimize your energy levels and overall health.', 78, 90, 93, 81, 'Charcoal Gray', 10, '8:00 AM', 'Climb steadily toward your peak today - every step upward increases your view of possibilities.'),

('2025-01-01', 11, 'Aquarius', 'Revolutionary ideas flow through you like an innovative philanthropist changing the world. Your unique perspective challenges conventional thinking and sparks progress.', 'Friendship-based romances evolve into deeper connections through shared humanitarian values.', 'Technology investments and group funding ventures align with future trends.', 'Your unconventional solutions to workplace challenges gain unexpected support.', 'Alternative health approaches yield surprising benefits for chronic concerns.', 84, 77, 82, 85, 'Electric Silver', 11, '3:33 PM', 'Think outside the box today - breakthrough solutions come from unexpected angles.'),

('2025-01-01', 12, 'Pisces', 'Intuitive wisdom flows like a brilliant physicist discovering universal truths through dreams. Your compassionate nature guides others toward healing and hope.', 'Spiritual connections transcend physical attraction, creating transcendent romantic experiences.', 'Artistic pursuits and creative investments show promise for both fulfillment and profit.', 'Your empathetic approach to colleagues creates a harmonious and productive work environment.', 'Water-based activities and meditation restore your energy and emotional balance.', 81, 74, 76, 90, 'Ocean Blue', 12, '5:55 AM', 'Follow your dreams today - your subconscious mind holds keys to mysteries others cannot solve.');

-- January 2, 2025 - Thursday
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-01-02', 1, 'Aries', 'Thursday''s energy amplifies your natural leadership like a fearless general rallying troops for victory. Initiative taken today creates momentum that lasts all month.', 'Direct communication strengthens romantic bonds more than subtle hints or games.', 'Quick decisive actions in financial matters prevent small problems from becoming large ones.', 'Your pioneering approach to challenges inspires team members to exceed expectations.', 'High-intensity workouts channel excess energy into positive physical transformation.', 85, 88, 87, 82, 'Bright Orange', 25, '7:15 AM', 'Strike while the iron is hot today - opportunities favor those who act with speed and confidence.'),

('2025-01-02', 2, 'Taurus', 'Like an artist perfecting their technique, you refine yesterday''s inspirations into concrete plans. Steady progress trumps rushed decisions in all endeavors.', 'Sensual pleasures and comfortable environments nurture romantic connections.', 'Traditional investment approaches yield more reliable returns than trendy alternatives.', 'Your reputation for dependability attracts new professional opportunities.', 'Gentle stretching and nature walks support your overall wellness better than intense exercise.', 79, 85, 84, 88, 'Moss Green', 16, '11:00 AM', 'Quality over quantity defines success today - focus on doing fewer things exceptionally well.'),

('2025-01-02', 3, 'Gemini', 'Your mental agility resembles a quick-witted diplomat navigating complex negotiations. Multiple conversations lead to unexpected connections and opportunities.', 'Variety in romantic activities keeps relationships fresh and intellectually stimulating.', 'Diverse investment portfolios protect against market volatility while maximizing growth.', 'Your networking abilities create collaborative opportunities across different industries.', 'Mental exercises and puzzles keep your mind sharp and stress levels manageable.', 88, 76, 89, 75, 'Bright Yellow', 37, '1:45 PM', 'Embrace versatility today - your ability to adapt quickly gives you distinct advantages.'),

('2025-01-02', 4, 'Cancer', 'Protective instincts guide you like a wise ruler safeguarding their people''s future. Family connections provide both comfort and valuable insights.', 'Emotional support and understanding deepen intimacy in existing relationships.', 'Family financial planning and home-related investments show excellent potential.', 'Your caring leadership style creates loyalty and dedication among team members.', 'Nutritious comfort foods and adequate sleep support your emotional and physical health.', 82, 80, 78, 91, 'Soft Blue', 4, '8:30 PM', 'Nurture what matters most today - your caring attention helps others flourish.'),

('2025-01-02', 5, 'Leo', 'Creative fire burns bright like a renowned performer perfecting their craft. Your artistic vision attracts admirers and potential collaborators.', 'Playful romance and creative dates strengthen bonds through shared joy and laughter.', 'Entertainment and luxury investments align with both pleasure and profit motives.', 'Your enthusiastic presentation of ideas wins over skeptical audiences.', 'Creative physical activities like dancing energize you more than routine exercise.', 90, 77, 86, 80, 'Sunset Orange', 23, '12:30 PM', 'Express your authentic self today - genuine creativity resonates more than perfect performance.'),

('2025-01-02', 6, 'Virgo', 'Analytical precision serves you like a dedicated reformer organizing systematic change. Details others miss become your pathway to excellence.', 'Practical romantic gestures demonstrate love more effectively than expensive displays.', 'Careful research into investment options reveals hidden gems with strong fundamentals.', 'Your systematic approach to complex problems earns recognition from senior management.', 'Preventive health measures and regular check-ups maintain optimal physical condition.', 73, 89, 92, 87, 'Sage Green', 9, '9:15 AM', 'Perfect your process today - systematic improvements compound into extraordinary results.'),

('2025-01-02', 7, 'Libra', 'Harmony-seeking nature resembles a musical composer creating perfect balance between opposing melodies. Aesthetic choices influence important decisions.', 'Mutual respect and fairness strengthen romantic partnerships through equal give-and-take.', 'Balanced portfolios and partnership investments provide stability with growth potential.', 'Your diplomatic skills resolve workplace conflicts before they escalate into major issues.', 'Balance between mental and physical activities maintains optimal energy and mood.', 84, 83, 85, 84, 'Lavender', 26, '3:00 PM', 'Seek equilibrium today - perfect balance creates the foundation for sustained success.'),

('2025-01-02', 8, 'Scorpio', 'Investigative instincts uncover hidden truths like a master detective solving complex mysteries. Psychological insights provide powerful advantages.', 'Intense emotional connections deepen through shared vulnerabilities and honest communication.', 'Research into undervalued investments reveals opportunities others have overlooked.', 'Your ability to see beneath surface issues makes you invaluable for strategic planning.', 'Detoxification and regenerative practices accelerate healing and renewal processes.', 91, 86, 89, 83, 'Midnight Black', 13, '10:45 PM', 'Dig deeper today - the most valuable treasures are hidden beneath obvious surfaces.'),

('2025-01-02', 9, 'Sagittarius', 'Expansive vision guides you like an explorer mapping uncharted territories of possibility. Educational pursuits open doors to future adventures.', 'Cross-cultural relationships and diverse perspectives enrich romantic experiences.', 'Educational investments and travel-related ventures promise long-term returns.', 'Your broad perspective helps teams see beyond immediate challenges to long-term solutions.', 'Outdoor activities and philosophical discussions energize both body and mind.', 86, 78, 83, 92, 'Forest Green', 31, '6:45 AM', 'Expand your horizons today - growth comes from venturing beyond familiar boundaries.'),

('2025-01-02', 10, 'Capricorn', 'Methodical progress resembles a master builder constructing enduring monuments. Each action today contributes to long-term achievement.', 'Traditional relationship values and commitment strengthen romantic bonds.', 'Conservative investment strategies and long-term planning show excellent stability.', 'Your disciplined work ethic sets the standard others aspire to match.', 'Structured fitness routines and consistent sleep patterns optimize your health.', 77, 91, 94, 79, 'Steel Gray', 15, '7:45 AM', 'Build systematically today - solid foundations support the highest achievements.'),

('2025-01-02', 11, 'Aquarius', 'Innovative thinking flows like a visionary inventor revolutionizing daily life. Unconventional approaches solve problems others find impossible.', 'Unique expressions of affection and non-traditional romantic activities deepen connections.', 'Technology stocks and innovative investments align with future market trends.', 'Your original ideas challenge conventional wisdom and inspire creative solutions.', 'Alternative health practices and experimental treatments show promising results.', 83, 75, 81, 88, 'Neon Green', 42, '2:15 PM', 'Innovate boldly today - your unconventional ideas are exactly what the world needs now.'),

('2025-01-02', 12, 'Pisces', 'Intuitive wisdom flows like a brilliant artist channeling divine inspiration into earthly creation. Dreams provide practical guidance for real-world decisions.', 'Spiritual and emotional connections transcend physical chemistry in romantic relationships.', 'Creative investments and artistic ventures show promise for both fulfillment and financial gain.', 'Your compassionate approach to difficult situations creates positive outcomes for everyone involved.', 'Meditation and water-based activities restore your energy and emotional equilibrium.', 80, 72, 74, 93, 'Sea Green', 18, '5:30 AM', 'Trust your instincts today - your inner voice speaks truths that logic cannot reach.');

-- January 3, 2025 - Friday (Completion Energy)
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-01-03', 1, 'Aries', 'Friday''s completion energy channels your drive like a triumphant conqueror finishing a decisive campaign. Week-ending achievements set the stage for weekend celebrations.', 'Bold romantic initiatives reach fruition, creating memorable moments of passion and connection.', 'Financial negotiations conclude favorably through your assertive yet fair approach.', 'Project deadlines met with excellence earn recognition and potential advancement opportunities.', 'Physical accomplishments boost confidence and motivate continued fitness commitment.', 91, 85, 88, 84, 'Victory Red', 27, '5:45 PM', 'Finish strong today - your Friday achievements create momentum for an inspiring weekend.'),

('2025-01-03', 2, 'Taurus', 'Like a master artisan completing a treasured creation, you bring projects to satisfying conclusions. Patient effort throughout the week yields tangible results.', 'Steady relationship building reaches new levels of trust and mutual understanding.', 'Conservative financial strategies prove their worth through consistent, reliable returns.', 'Your methodical work approach delivers quality results that exceed client expectations.', 'Gradual fitness improvements become noticeable, encouraging continued healthy habits.', 82, 89, 86, 87, 'Earth Brown', 20, '4:30 PM', 'Savor your accomplishments today - steady progress creates lasting satisfaction.'),

('2025-01-03', 3, 'Gemini', 'Communication mastery shines like an eloquent speaker delivering the perfect closing argument. Multiple conversations reach successful resolutions.', 'Witty banter and intellectual connections create romantic sparks with promising potential.', 'Diverse financial strategies pay off as multiple income streams reach profitable levels.', 'Your networking efforts throughout the week culminate in valuable partnership opportunities.', 'Mental stimulation energizes you more than physical exertion on this cerebral day.', 87, 79, 91, 76, 'Electric Yellow', 35, '3:15 PM', 'Connect the dots today - your ability to see patterns others miss creates breakthrough insights.'),

('2025-01-03', 4, 'Cancer', 'Nurturing efforts reach full bloom like a devoted caregiver seeing loved ones flourish. Family dynamics achieve new levels of harmony and support.', 'Emotional intimacy deepens through vulnerable sharing and compassionate listening.', 'Home-based investments and family financial planning show excellent long-term potential.', 'Your empathetic leadership helps team members overcome challenges and achieve group goals.', 'Emotional wellness practices create a strong foundation for overall health and vitality.', 85, 83, 80, 92, 'Moonlight Silver', 3, '7:15 PM', 'Nurture connections today - your caring attention helps relationships reach new depths.'),

('2025-01-03', 5, 'Leo', 'Creative brilliance reaches peak expression like a celebrated performer delivering their signature piece. Artistic endeavors gain recognition and applause.', 'Dramatic romantic gestures create unforgettable moments that strengthen passionate bonds.', 'Creative investments and entertainment ventures show promise for both joy and profit.', 'Your enthusiastic leadership inspires team members to deliver their absolute best work.', 'Performance-based activities and creative expression energize both body and spirit.', 93, 81, 87, 82, 'Golden Yellow', 17, '1:00 PM', 'Shine brilliantly today - your authentic radiance inspires others to discover their own light.'),

('2025-01-03', 6, 'Virgo', 'Perfectionist nature achieves remarkable results like a dedicated scientist making groundbreaking discoveries through meticulous research. Details create excellence.', 'Practical expressions of love through helpful actions deepen romantic appreciation.', 'Careful financial analysis reveals optimal investment opportunities with minimal risk.', 'Your attention to quality standards ensures project outcomes exceed all expectations.', 'Preventive health measures and organized wellness routines optimize physical condition.', 76, 92, 95, 89, 'Pure White', 6, '8:45 AM', 'Perfect your craft today - excellence emerges from thousands of small improvements.'),

('2025-01-03', 7, 'Libra', 'Diplomatic excellence creates harmony like a skilled mediator bringing opposing sides to peaceful agreement. Balance pervades all interactions.', 'Romantic relationships achieve perfect equilibrium through mutual respect and compromise.', 'Balanced investment portfolios provide both stability and growth through careful diversification.', 'Your fair-minded approach to workplace conflicts creates win-win solutions for everyone.', 'Balanced activities between mental and physical pursuits maintain optimal energy levels.', 88, 84, 86, 85, 'Peaceful Pink', 24, '2:45 PM', 'Create harmony today - your gift for balance brings beauty and peace to chaotic situations.'),

('2025-01-03', 8, 'Scorpio', 'Transformative power reaches crescendo like a revolutionary artist unveiling their masterpiece. Hidden depths surface with profound impact.', 'Intense emotional revelations deepen romantic connections through authentic vulnerability.', 'Investigative research uncovers undervalued investments with tremendous growth potential.', 'Your penetrating insights into complex problems lead to comprehensive solutions.', 'Deep healing work and transformative practices accelerate recovery and renewal.', 92, 88, 90, 86, 'Deep Crimson', 8, '11:11 PM', 'Transform boldly today - your courage to change creates ripples that inspire others.'),

('2025-01-03', 9, 'Sagittarius', 'Adventurous spirit soars like an explorer discovering magnificent new worlds. Philosophical insights expand understanding and inspire future journeys.', 'Cultural exploration and diverse experiences enrich romantic relationships with fresh perspectives.', 'International investments and educational ventures reach profitable completion.', 'Your visionary ideas inspire teams to achieve beyond their previously imagined limitations.', 'Adventure-based fitness activities combine physical exercise with mental stimulation.', 89, 80, 84, 94, 'Adventurous Orange', 32, '6:15 AM', 'Explore fearlessly today - the greatest discoveries await beyond the edges of your comfort zone.'),

('2025-01-03', 10, 'Capricorn', 'Ambitious determination reaches milestone achievement like a mountain climber conquering their highest peak. Persistent effort yields prestigious recognition.', 'Mature relationships strengthen through shared accomplishments and mutual professional respect.', 'Long-term investment strategies demonstrate their wisdom through steady, substantial returns.', 'Your disciplined work ethic and strategic planning earn promotion or significant advancement.', 'Structured fitness routines and consistent health practices show measurable positive results.', 80, 93, 96, 81, 'Professional Navy', 10, '9:00 AM', 'Claim your summit today - your persistent effort has earned you the right to celebrate achievement.'),

('2025-01-03', 11, 'Aquarius', 'Revolutionary ideas reach implementation like an innovative inventor seeing their vision transform society. Unique approaches create breakthrough solutions.', 'Unconventional romantic expressions and alternative relationship styles deepen unusual connections.', 'Technology investments and futuristic ventures show early signs of significant returns.', 'Your original thinking patterns solve problems that have stumped conventional approaches.', 'Alternative health practices and experimental treatments yield surprisingly positive results.', 86, 77, 83, 90, 'Electric Blue', 44, '4:44 PM', 'Revolutionize today - your unconventional wisdom is exactly what stagnant situations need.'),

('2025-01-03', 12, 'Pisces', 'Mystical intuition reaches prophetic clarity like a wise mystic channeling universal truths. Dreams and reality merge into practical wisdom.', 'Soul-level connections transcend physical chemistry, creating transcendent romantic experiences.', 'Artistic investments and creative ventures demonstrate their value through both beauty and profit.', 'Your compassionate leadership helps colleagues navigate emotional challenges with grace.', 'Water-based activities and meditative practices restore perfect emotional and physical balance.', 83, 75, 77, 95, 'Mystic Purple', 12, '5:55 AM', 'Flow with intuition today - your inner wisdom reveals solutions that logic cannot discover.');

-- January 4, 2025 - Saturday (Weekend Reflection Energy)
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-01-04', 1, 'Aries', 'Saturday''s reflective energy tempers your fire like a wise warrior considering strategy between battles. Rest recharges your ambitious spirit for next week''s conquests.', 'Spontaneous romantic adventures create lasting memories and strengthen passionate connections.', 'Weekend market research reveals investment opportunities for Monday action.', 'Personal projects and creative pursuits provide satisfying outlets for your energy.', 'Active rest through enjoyable physical activities maintains fitness while preventing burnout.', 86, 78, 75, 88, 'Warm Coral', 28, '10:30 AM', 'Balance action with reflection today - even warriors need time to sharpen their swords.'),

('2025-01-04', 2, 'Taurus', 'Like a content artist enjoying the fruits of their labor, you savor weekend pleasures and simple joys. Comfort and beauty restore your practical spirit.', 'Cozy intimate moments and sensual pleasures deepen romantic bonds through shared comfort.', 'Leisurely financial planning and budget reviews set foundations for future security.', 'Home-based projects and creative hobbies provide fulfilling outlets for your talents.', 'Gentle movement and nutritious comfort foods maintain health while honoring your need for ease.', 90, 85, 70, 92, 'Warm Beige', 5, '2:00 PM', 'Embrace comfort today - taking time to enjoy life''s pleasures recharges your productive spirit.'),

('2025-01-04', 3, 'Gemini', 'Weekend socializing energizes you like a brilliant conversationalist hosting the perfect salon. Diverse connections spark new ideas and opportunities.', 'Multiple social interactions create romantic possibilities through expanded networks.', 'Casual financial conversations with friends reveal interesting investment insights.', 'Networking events and social gatherings plant seeds for future professional collaborations.', 'Mental stimulation through varied activities energizes you more than physical exercise.', 88, 73, 77, 79, 'Bright Lime', 39, '4:15 PM', 'Socialize strategically today - your gift for connection turns casual conversations into golden opportunities.'),

('2025-01-04', 4, 'Cancer', 'Family time nourishes your soul like a loving parent gathering their clan for meaningful connection. Home becomes your sanctuary of strength.', 'Family gatherings and intimate home settings create perfect romantic atmospheres.', 'Family financial discussions and shared planning strengthen economic security for all.', 'Home-based work and family business opportunities show promising potential.', 'Comfort foods and emotional nurturing restore your physical and mental energy.', 85, 82, 68, 94, 'Gentle Blue', 2, '6:45 PM', 'Cherish family today - your nurturing presence creates the foundation others need to flourish.'),

('2025-01-04', 5, 'Leo', 'Creative expression flows freely like a celebrated artist in their private studio. Weekend projects showcase your talents and bring personal satisfaction.', 'Playful romantic creativity and entertaining dates strengthen bonds through shared joy.', 'Creative side hustles and artistic investments show early signs of profitability.', 'Personal branding and creative projects build your reputation for future opportunities.', 'Fun physical activities and creative movement maintain fitness while expressing your personality.', 92, 80, 74, 85, 'Radiant Gold', 1, '12:15 PM', 'Create joyfully today - your authentic self-expression inspires others to embrace their own uniqueness.'),

('2025-01-04', 6, 'Virgo', 'Organized leisure activities satisfy like a master craftsperson maintaining their workshop. Even rest becomes productive through thoughtful planning.', 'Practical romantic activities and helpful gestures demonstrate love through caring service.', 'Weekend budget organization and systematic financial reviews improve money management.', 'Home organization and skill-building projects prepare you for professional advancement.', 'Systematic health routines and preventive care maintain optimal physical condition.', 77, 88, 84, 91, 'Clean White', 11, '9:30 AM', 'Organize thoughtfully today - systematic approach to leisure creates both rest and progress.'),

('2025-01-04', 7, 'Libra', 'Aesthetic pleasures and social harmony create perfect weekend balance like an artist arranging beautiful compositions. Beauty feeds your soul.', 'Romantic settings and aesthetic experiences deepen connections through shared appreciation of beauty.', 'Artistic investments and beauty-related purchases prove both enjoyable and financially sound.', 'Creative collaborations and partnership projects advance through harmonious weekend planning.', 'Balanced activities between social and solitary pursuits maintain optimal energy and mood.', 89, 81, 76, 87, 'Soft Rose', 26, '3:30 PM', 'Seek beauty today - surrounding yourself with harmony restores your spirit and inspires others.'),

('2025-01-04', 8, 'Scorpio', 'Deep transformation continues like a phoenix rising from ashes in private contemplation. Weekend solitude allows profound inner work.', 'Intimate emotional sharing and psychological intimacy deepen romantic connections.', 'Private financial research and strategic planning uncover hidden investment opportunities.', 'Behind-the-scenes work and strategic planning prepare for powerful professional moves.', 'Detoxification and regenerative practices accelerate healing and renewal during rest time.', 90, 87, 72, 89, 'Deep Burgundy', 9, '9:45 PM', 'Transform privately today - your inner work creates the foundation for outer success.'),

('2025-01-04', 9, 'Sagittarius', 'Adventure calls like an explorer planning expeditions to distant lands. Weekend travels or philosophical pursuits expand your horizons.', 'Cultural activities and diverse experiences create romantic adventures with lasting memories.', 'Travel-related expenses and educational investments promise long-term returns and growth.', 'Learning new skills and exploring different fields prepare you for future career expansion.', 'Outdoor adventures and physical exploration energize both body and adventurous spirit.', 87, 76, 78, 93, 'Adventure Blue', 34, '7:00 AM', 'Explore freely today - your weekend adventures plant seeds for future growth and opportunity.'),

('2025-01-04', 10, 'Capricorn', 'Strategic rest prepares you like a general planning victory while troops recover. Even leisure serves your long-term ambitions.', 'Traditional romantic activities and committed relationship building strengthen lasting bonds.', 'Weekend financial planning and long-term investment reviews ensure continued stability.', 'Strategic career planning and skill development during rest time advance professional goals.', 'Structured relaxation and consistent health routines maintain peak performance capacity.', 81, 91, 82, 84, 'Classic Navy', 15, '8:15 AM', 'Plan strategically today - thoughtful weekend preparation creates advantages for the coming week.'),

('2025-01-04', 11, 'Aquarius', 'Unconventional weekend activities energize you like an inventor experimenting with revolutionary ideas. Innovation never rests.', 'Unique romantic experiences and alternative activities create memorable unconventional connections.', 'Technology investments and futuristic financial strategies show early positive indicators.', 'Experimental projects and innovative thinking during downtime generate breakthrough solutions.', 'Alternative wellness practices and experimental health approaches yield surprising benefits.', 84, 74, 80, 90, 'Electric Violet', 47, '1:11 PM', 'Innovate casually today - your most revolutionary ideas often emerge during relaxed experimentation.'),

('2025-01-04', 12, 'Pisces', 'Spiritual renewal flows like a mystic connecting with universal consciousness. Weekend dreams provide guidance for practical decisions.', 'Spiritual romantic connections and soulful intimacy transcend physical chemistry.', 'Intuitive financial insights and artistic investment opportunities show promise through inner guidance.', 'Creative projects and compassionate service work provide fulfilling outlets for your talents.', 'Water activities and meditative practices restore perfect emotional and spiritual balance.', 82, 71, 73, 96, 'Oceanic Teal', 7, '5:00 AM', 'Flow spiritually today - your connection to higher wisdom provides guidance others cannot access.');