-- Key Special Date Examples for Q1 2025 Daily Fortune System
-- Demonstrating Korean Holiday Themes and Special Date Patterns

-- January 28, 2025 - 설날 (Lunar New Year) Day 1 - Tuesday
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-01-28', 1, 'Aries', '설날의 새로운 시작 에너지가 당신의 개척 정신을 불러일으킵니다. Like a brave ancestor honoring tradition while forging new paths, you blend respect for the past with courage for the future.', 'Family gatherings create opportunities for introducing romantic partners to ancestral traditions.', 'Traditional investments and heritage-based financial planning show excellent lunar year potential.', 'Leadership in cultural celebrations showcases your ability to honor tradition while inspiring innovation.', 'Traditional foods and family recipes provide both nourishment and emotional connection to heritage.', 95, 88, 85, 90, 'Traditional Red', 8, '6:00 AM', '새해 복 많이 받으세요! Honor your ancestors while boldly creating your own legacy.'),

('2025-01-28', 4, 'Cancer', '설날의 가족 중심 에너지가 당신의 nurturing heart를 강화합니다. Like a devoted family matriarch preserving traditions for future generations, you create lasting bonds through cultural connection.', 'Family celebrations deepen romantic relationships through shared cultural values and traditions.', 'Lunar New Year bonuses and family financial gifts create unexpected prosperity and security.', 'Your role in organizing family celebrations demonstrates natural leadership and organizational skills.', 'Traditional healing foods and ancestral recipes restore both physical health and emotional well-being.', 94, 85, 80, 95, 'Lunar Gold', 3, '8:30 PM', '가족의 사랑이 당신의 힘입니다. Family love provides the foundation for all your achievements.'),

('2025-01-28', 10, 'Capricorn', '설날의 전통과 성취가 당신의 ambitious nature와 완벽하게 조화됩니다. Like a successful businessman honoring ancestors while building empire, you understand that respect for tradition creates future success.', 'Traditional relationship values and family approval strengthen romantic commitments and future plans.', 'Lunar New Year investments and traditional financial wisdom prove their value through consistent returns.', 'Your reputation for reliability and tradition makes you the natural choice for leadership positions.', 'Traditional health practices and ancestral wisdom complement modern wellness approaches perfectly.', 92, 94, 88, 87, 'Royal Purple', 9, '9:00 AM', '전통이 미래를 만듭니다. Tradition creates the foundation upon which future success is built.');

-- February 14, 2025 - Valentine's Day - Friday
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-02-14', 5, 'Leo', 'Valentine''s Day amplifies your romantic radiance like a legendary lover whose passion inspires poetry and art. Your dramatic gestures create unforgettable memories.', 'Grand romantic displays and theatrical expressions of love create magical moments that strengthen deep bonds.', 'Love-related investments and romantic business ventures show promising returns through emotional connections.', 'Your charismatic presentation of ideas wins hearts and minds in professional romantic partnerships.', 'Activities that make your heart race with joy energize both romantic spirit and physical vitality.', 98, 82, 86, 88, 'Passionate Red', 14, '7:30 PM', 'Love boldly today - your authentic romantic expression inspires others to open their hearts fearlessly.'),

('2025-02-14', 7, 'Libra', 'Valentine''s harmony flows through you like a master of romance creating perfect balance between passion and elegance. Beauty and love converge magnificently.', 'Perfect romantic balance emerges through equal expressions of love, creating harmonious valentine celebrations.', 'Partnership investments and shared financial goals benefit from valentine''s day collaborative energy.', 'Your ability to create beautiful presentations and harmonious team dynamics advances romantic professional projects.', 'Balanced romantic activities that please both heart and mind maintain optimal emotional and physical health.', 96, 85, 83, 89, 'Rose Gold', 2, '2:14 PM', 'Create romantic harmony today - your gift for balance makes love beautiful for everyone around you.'),

('2025-02-14', 12, 'Pisces', 'Valentine''s mystical love energy flows through you like a romantic poet channeling divine inspiration. Your intuitive understanding of love transcends ordinary expression.', 'Soul-deep romantic connections and spiritual intimacy create transcendent valentine experiences beyond physical chemistry.', 'Love-inspired creative investments and romantic artistic ventures show promise through intuitive financial guidance.', 'Your compassionate approach to workplace relationships creates romantic harmony that benefits entire teams.', 'Love-centered meditation and heart-opening practices restore perfect romantic and spiritual balance.', 97, 78, 81, 92, 'Mystic Pink', 12, '11:11 AM', 'Love mystically today - your intuitive understanding of romance reveals love''s deepest mysteries.');

-- March 1, 2025 - 삼일절 (Independence Movement Day) - Saturday
INSERT INTO daily_fortunes (date, zodiac_id, zodiac_name, overall_fortune, love_fortune, money_fortune, work_fortune, health_fortune, love_score, money_score, work_score, health_score, lucky_color, lucky_number, lucky_time, daily_advice) VALUES
('2025-03-01', 1, 'Aries', '삼일절의 독립 정신이 당신의 개척자 성격과 완벽하게 맞아떨어집니다. Like a fearless independence leader fighting for freedom, you champion causes that liberate others from limitations.', 'Independent romantic choices and freedom from relationship constraints strengthen authentic love connections.', 'Financial independence strategies and liberation from debt create pathways to economic freedom.', 'Your leadership in independence projects and freedom initiatives earns recognition and advancement.', 'Physical freedom through outdoor activities and liberation from unhealthy habits energize your warrior spirit.', 93, 87, 91, 85, 'Freedom Blue', 31, '10:00 AM', '자유를 위해 싸우세요! Fight for freedom - your courage to lead independence movements inspires others to break their chains.'),

('2025-03-01', 11, 'Aquarius', '삼일절의 혁명 정신이 당신의 humanitarian vision을 불러일으킵니다. Like a revolutionary thinker inspiring social change, you understand that true independence comes through collective liberation.', 'Revolutionary approaches to romance and unconventional relationship freedom create unique independence celebrations.', 'Investment in social causes and independence movements shows promise for both conscience and profit.', 'Your innovative solutions to workplace freedom and independence issues gain widespread support.', 'Alternative health approaches and liberation from conventional medical limitations show surprising independence benefits.', 91, 83, 89, 90, 'Revolutionary Red', 19, '3:01 PM', '혁명을 일으키세요! Start revolutions - your vision of independence creates freedom for entire communities.'),

('2025-03-01', 9, 'Sagittarius', '삼일절의 자유 정신이 당신의 adventurous soul과 resonates합니다. Like an explorer discovering new lands of freedom, you understand that independence requires courage to venture beyond known boundaries.', 'Freedom in romantic relationships and independent love adventures create liberation from conventional relationship constraints.', 'International investments and freedom-based financial strategies promise independence from economic limitations.', 'Your visionary ideas about workplace independence and freedom inspire teams to achieve beyond traditional limits.', 'Adventure-based freedom activities and liberation from indoor constraints energize both independence spirit and physical health.', 89, 81, 87, 94, 'Liberty Gold', 1, '6:30 AM', '자유롭게 탐험하세요! Explore freely - your adventures in independence lead others to discover their own liberation.');